### ISSUE TITLE
doc page  content is moveit1 ros1，please  fix to moveit2 ros2

### ISSUE THREAD

**Issue by zouzhe1** [ros-planning/moveit2_tutorials#764] opened 2023-09-13 01:41 UTC
### Description

doc page  content is moveit1 ros1，please  fix to moveit2 ros2

### Your environment
* ROS Distro: [Humble]
* OS Version: e.g. Ubuntu 22.04

### link

https://github.com/ros-planning/moveit2_tutorials/blob/main/doc/examples/subframes/subframes_tutorial.rst

https://moveit.picknik.ai/main/doc/examples/subframes/subframes_tutorial.html

**Comment by sea-bass** [comment] 2023-09-13 01:45
This is a duplicate of https://github.com/ros-planning/moveit2_tutorials/issues/19.

**Closed by sea-bass** 2023-09-13 01:45 UTC
