### ISSUE TITLE
Build warning re. std::shared_future

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit2_tutorials#122] opened 2021-09-28 16:00 UTC
warning: ‘rclcpp::Client<ServiceT>::FutureAndRequestId::operator rclcpp::Client<ServiceT>::SharedFuture() [with ServiceT = moveit_msgs::srv::ApplyPlanningScene; rclcpp::Client<ServiceT>::SharedFuture = std::shared_future<std::shared_ptr<moveit_msgs::srv::ApplyPlanningScene_Response_<std::allocator<void> > > >; typename ServiceT::Response::SharedPtr = std::shared_ptr<moveit_msgs::srv::ApplyPlanningScene_Response_<std::allocator<void> > >]’ is deprecated: FutureAndRequestId: use .future.share() instead of an implicit conversion [-Wdeprecated-declarations]
  175 |   response_future = planning_scene_diff_client->async_send_request(request);

The message pretty much says how to fix it.

**Comment by tlpss** [comment] 2021-09-28 20:08
@AndyZe you can assign this one to me. Could you specify the tutorial where you encountered this warning?

**Comment by AndyZe** [comment] 2021-09-29 19:40
Sorry I don't remember which tutorial it was. If you follow the "Getting Started" steps to clone and build the tutorials from scratch, I bet you will see the warning.

http://moveit2_tutorials.picknik.ai/doc/getting_started/getting_started.html

**Comment by tlpss** [comment] 2021-10-04 08:00
@AndyZe  I reinstalled the tutorials by following the getting_started page but could not reproduce the warning. Everything seems to build fine without warnings on my system. 

I believe the warning refers to:  https://github.com/ros-planning/moveit2_tutorials/blob/f99b7eb0591adf4ab7c3eba21f03a653d7c8cfa5/doc/planning_scene_ros_api/src/planning_scene_ros_api_tutorial.cpp#L174

**Comment by vatanaksoytezer** [comment] 2021-10-04 12:36
@tlpss this is the correct line to look at. The warning is still here in Rolling: https://github.com/ros-planning/moveit2_tutorials/runs/3785281390?check_suite_focus=true#step:6:224

**Comment by tlpss** [comment] 2021-10-19 15:34
@AndyZe, I finally found some time to get acquainted with vscode dev containers, which I was waiting for to create a ros2 rolling workspace. Apologies for the radio silence.  

I fixed the deprecation warning by doing an explicit conversion and made a PR

**Closed** 2021-11-02 13:10 UTC
Labels: good first issue
